default_lang: en

host: "http://localhost:5001"

## Uncomment when audit messages need to be displayed
# audit: 1

urn_prefix: 'urn:test-'

## Specity the ipranges which can download (local) files
ip_range:
    - 157.193.0.0/16
    - 127.0.0.1
    - 10.0.0.0/8

authentication:
  package: LibreCat::Auth::Multi
  options:
    methods:
      # password auth against users in config
      - package: LibreCat::Auth::Bag
        options:
          store: builtin_users
          username_attr: login
      # password auth against database users
      - package: LibreCat::Auth::Bag
        options:
          store: search
          bag: user
          username_attr: login

user:
  sources:
    - store: builtin_users
      username_attr: login
    - store: search
      bag: user
      username_attr: login

citation:
  engine: none

store:
  main:
    package: DBI
    options:
      data_source: "dbi:SQLite:dbname=t/tmp/librecat_test.sqlite3"

  search:
    options:
      client: '1_0::Direct'
      index_name: librecat_test
  builtin_users:
    package: Hash
    options:
      init_data:
        # stored password authentication
        - login: einstein
          # password is same as login
          # crypt a password with 'bmkpasswd [password]' in the shell
          password: '$2a$08$p1zhJInkNqy9nvMFsEPde./hU4ERNQuX2UQUjZA/ddrp1uUXikn/6'
          _id: 1234
          super_admin: 1
          account_status: active

filestore:
    default: &filestore_settings
        package: Simple
        options:
            root: t/data
    test:
        package: Simple
        options:
            root: t/data2
    uploader:
        package: 'LibreCat::Worker::FileUploader'
        options:
            files: *filestore_settings
hooks:
  eat:
   before_fixes: [peckish, hungry]
   after_fixes: [satisfied]

i18n:
  lexicon:
    en:
      - CatmanduConfig
      - ['en']

locale:
  en:
    hello: How are you?

queue:
  workers:
    audit:
      count: 1
      supervise: 1

worker:
    logdir: /tmp
