sudo: required
dist: trusty
language: perl

perl:
  - "5.22"
  - "5.20"

cache:
  directories:
    - perl_modules

env:
  - NETWORK_TEST=1 GEARMAN_NETWORK_TEST=1

before_install:
 - curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.7.5.deb && sudo dpkg -i --force-confnew elasticsearch-1.7.5.deb && sudo service elasticsearch restart
  - sudo apt-get install --yes --force-yes gearman gearman-job-server libgearman-dev gearman-tools
  - cpanm local::lib
  - eval "$(perl -Mlocal::lib=${PWD}/perl_modules)"

before_script:
  - sleep 3

services:
  - sqlite3

install:
  - cpanm --quiet --installdeps --notest --force --skip-satisfied . || cat /home/travis/.cpanm/*/build.log
  - cpanm --quiet --notest --skip-satisfied Devel::Cover
  - cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Coveralls

matrix:
  include:
    perl: "5.24"
    script:
      - cover -t +select ^lib +ignore ^ -make 'prove -Ilib -r t; exit $?'

script:
  - prove -Ilib -r t/

after_success:
  - cover -report coveralls

notifications:
  email: false
  slack: librecat:2Rvl147KSMvEdivUg88Ktrbk
