web:
  image: librecat
  command: ["plackup","-p","5000","bin/app.pl"]
  ports:
    - "5000:5000"
  volumes:
    - ".:/code"
  links:
    - elasticsearch
    - mongodb
elasticsearch:
  image: elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
  volumes:
    - "$PWD/data/es:/usr/share/elasticsearch/data"
mongodb:
  image: mongo
  ports:
    - "27017:27017"
  volumes:
    - "$PWD/data/mongo:/data"
