version: "3.7"

services:

  elasticsearch:
    # See: https://www.elastic.co/guide/en/elasticsearch/reference/7.5/docker.html for more optionss
    image: elasticsearch:6.8.12
    hostname: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
    volumes:
      - "esdata:/usr/share/elasticsearch/data"

  mysql:
      image: mysql:5.7
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      ports:
          - 3306:3306
      environment:
          MYSQL_ROOT_PASSWORD: librecat
      volumes:
        - "mydata:/var/lib/mysql"

  # librecat:
  #    image: librecat/librecat:latest
  #    hostname: librecat
  #    ports:
  #      - 5002:5002
  #    environment:
  #        MYSQL_ROOT_PASSWORD: librecat
  #        LIBRECAT_PORT: 5002
  #        LIBRECAT_INIT: 1
  #        LIBRECAT_DEMO: 1
  #        LIBRECAT_ENV: deployment
  #        LIBRECAT_LAYER: mylayer
  #        WAIT_HOSTS: mysql:3306, elasticsearch:9200
  #        WAIT_HOSTS_TIMEOUT: 60
  #    volumes:
  #      - ./mylayer:/opt/librecat/mylayer

volumes:
    esdata:
    mydata:
