version: "3.7"

services:
  elasticsearch:
    image: elasticsearch:6.8.12
    hostname: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node

  mysql:
      image: mysql:5.7
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      ports:
          - 3306:3306
      environment:
          MYSQL_ROOT_PASSWORD: librecat

  # librecat:
  #    image: librecat/librecat:latest
  #    hostname: librecat
  #    ports:
  #      - 5002:5002
  #    environment:
  #        MYSQL_ROOT_PASSWORD: librecat
  #        LIBRECAT_PORT: 5002
  #        LIBRECAT_INIT: 1
  #        LIBRECAT_DEMO: 1
  #        LIBRECAT_ENV: deployment
