time_format: "%Y-%m-%dT%H:%M:%SZ"

ip_range: '8.8'

urn_prefix: 'urn:whatever-'

thesis:
  to: 'send@me.org'
  from: 'from@you.org'
  subject: '[PUB] New thesis submitted'
  urn_prefix: 'urn:thesis-'

# datacite test prefix!
doi:
  prefix: "10.5072/test"
  user: user
  passwd: secret

# authentication
authentication:
  param:
    host: 'yourldaphost'
    auth_base: 'uid=%s,ou=People,o=elearning-user,o=Uni-Bi'

# default settings
default_lang: en
default_page_size: 20
default_searchpage_size: 10
maximum_page_size: 1000
pagination_options:
  - 10
  - 20
  - 50
  - 100
sort_options:
  - year
  - date_updated
  - title
  - author
  - type
  - publication
sort_options_person:
  - fullname
  - publcount
project_sort_options:
  - name
  - acronym
  - startyear
default_sort:
  - year.desc
  - date_updated.desc
default_sort_backend:
  - date_updated.desc
  - year.desc
default_style: 'default'
default_fd_style: 'default'
default_format: html

request_copy:
# period in days
  period: 7
  subject: 'Request for a copy of your publication'
