_prefix:
  citation:

# engine for citation generation
# possible values are 'template' or 'csl'
engine: template

template:
  template_path: 'views/citation.tt'

csl:
  url: 'http://::/CiteprocPhp/CiteProc.php' #absolute url
  default_style: 'default'
  styles:
    - ama
    - angewandte-chemie
    - apa
    - apa_indent
    - aps
    - bio1
    - chicago
    - default
    - dgps
    - frontiers
    - harvard1
    - ieee
    - lncs
    - mla
    - wels
