_prefix:
  citation:

# engine for citation generation
# possible values are 'template' or 'csl' or 'none'
engine: none

template:
  template_path: 'views/citation.tt'

csl:
  url: 'http://localhost:8085'
  default_style: apa
  styles:
    - modern-language-association
    - chicago-fullnote-bibliography
    - american-medical-association
    - angewandte-chemie
    - apa
    - ieee
