_prefix:
  form_handlers:

fh_new_research_group:
  before_fixes: []
  after_fixes: []
  fields:
    #TODO: refer to actual I18N keys instead of using these literal strings
    - name: name
      label: Name
      type: Text
      required: 1
      messages:
        required: "Name is required"
    - name: acronym
      label: Acronym
      type: Text
    #TODO: translate error message "Your datetime does not match your pattern." from DateTime::Format::Strptime
    - name: start_date
      label: "Start date"
      type: Date
      format: "%Y-%m-%d"
    - name: end_date
      label: "End date"
      type: Date
      format: "%Y-%m-%d"
    - name: affiliation
      label: Affiliation
      type: Repeatable
      add_extra: 1
      num_when_empty: 1
    - name: affiliation.contains
      type: Text
