log4perl: |
  log4perl.category.LibreCat::App=INFO,FILE
  log4perl.category.LibreCat::Auth=INFO,STDERR,FILE
  log4perl.category.LibreCat::Hook=INFO,FILE
  log4perl.category.LibreCat::FetchRecord=INFO,FILE
  log4perl.category.LibreCat::Model=INFO,FILE
  log4perl.category.LibreCat::Search=INFO,FILE
  log4perl.category.LibreCat::App::Catalogue::Controller::File=INFO,STDERR,FILE
  log4perl.appender.STDERR=Log::Log4perl::Appender::Screen
  log4perl.appender.STDERR.stderr=1
  log4perl.appender.STDERR.utf8=1
  log4perl.appender.STDERR.layout=PatternLayout
  log4perl.appender.STDERR.layout.ConversionPattern=%d %p [%P] - %c[%L] : %m%n
  log4perl.appender.FILE=Log::Log4perl::Appender::File
  log4perl.appender.FILE.filename=./logs/app.log
  log4perl.appender.FILE.utf8=1
  log4perl.appender.FILE.layout=PatternLayout
  log4perl.appender.FILE.layout.ConversionPattern=%d %p [%P] - %c[%L] : %m%n
