log4perl: |
  log4perl.category.LibreCat::Auth=INFO,STDERR,FILE
  log4perl.category.LibreCat::FileStore=INFO,STDERR,FILE
  log4perl.category.LibreCat::Worker=INFO,STDERR,FILE
  log4perl.category.LibreCat::App=INFO,FILE
  log4perl.appender.STDERR=Log::Log4perl::Appender::Screen
  log4perl.appender.STDERR.stderr=1
  log4perl.appender.STDERR.utf8=1
  log4perl.appender.STDERR.layout=PatternLayout
  log4perl.appender.STDERR.layout.ConversionPattern=%d [%P] - %c[%L] : %m%n
  log4perl.appender.FILE=Log::Log4perl::Appender::File
  log4perl.appender.FILE.filename=app.log
  log4perl.appender.FILE.layout=PatternLayout
  log4perl.appender.FILE.layout.ConversionPattern=%d [%P] - %c[%L] : %m%n
