_prefix:
  permissions:

login_route: /login
logged_in_key: user
callback_key: return_url
passthrough:
    - user

routes:
    - [ 'GET'  , '/librecat/record/new'           , 'login' ]
    - [ 'GET'  , '/librecat/record/edit'          , 'login' ]
    - [ 'POST' , '/librecat/record/update'        , 'login' ]
    - [ 'GET'  , '/librecat/record/return'        , 'login' ]
    - [ 'GET'  , '/librecat/record/delete'        , 'role' , 'super_admin' ]
    - [ 'GET'  , '/librecat/record/preview'       , 'login' ]
    - [ 'GET'  , '/librecat/record/internal_view' , 'role' , 'super_admin' ]
    - [ 'GET'  , '/librecat/record/clone'         , 'login' ]
    - [ 'GET'  , '/librecat/record/publish'       , 'login' ]
    - [ 'POST' , '/librecat/record/change_mode'   , 'login' ]
    - [ 'POST' , '/librecat/record/import'        , 'login' ]

    - [ 'GET'  , '/librecat/search/admin'         , 'role' , 'super_admin' ]
    - [ 'GET'  , '/librecat/search/reviewer'      , 'role' , 'reviewer' ]
    - [ 'GET'  , '/librecat/search/project_reviewer' , 'role' , 'project_reviewer' ]
    - [ 'GET'  , '/librecat/search/data_manager'  , 'role' , 'data_manager' ]
    - [ 'GET'  , '/librecat/search/delegate'      , 'role' , 'delegate' ]
    - [ 'GET'  , '/librecat/search/data'          , 'login' ]
    - [ 'GET'  , '/librecat/search'               , 'login' ]
    - [ 'GET'  , '/librecat/change_role'          , 'login' ]

    - [ 'POST' , '/librecat/upload'               , 'login' ]
    - [ 'POST' , '/librecat/upload/qae/submit'    , 'login' ]

    - [ 'GET'  , '/librecat/admin/project/search'          , 'login' ]
    - [ 'GET'  , '/librecat/admin/department/search'       , 'login' ]
    - [ 'GET'  , '/librecat/admin/research_group/search'   , 'login' ]
    - [ 'ANY'  , '/librecat/admin'               , 'role' , 'super_admin' ]

    - [ 'ANY'  , '/librecat/audit'               , 'role' , 'super_admin' ]

    - [ 'GET'  , '/librecat/person/preference/\S+' , 'role' , 'delegate' ]
    - [ 'GET'  , '/librecat/person/preference'   , 'login'  ]
    - [ 'POST' , '/librecat/person/author_id'    , 'login'  ]
    - [ 'GET'  , '/librecat/person/set_language' , 'login'  ]
    - [ 'POST' , '/librecat/person/affiliation'  , 'login'  ]

    - [ 'ANY'  , '/librecat/api'                 , 'api_access' ]

    - [ 'ANY'  , '/metrics'                      , 'default' ]
    - [ 'ANY'  , '/bibtex '                      , 'default' ]
    - [ 'ANY'  , '/ris '                         , 'default' ]
    - [ 'ANY'  , '/search_researcher '           , 'default' ]
    - [ 'ANY'  , '/authority_user'               , 'default' ]
    - [ 'ANY'  , '/num_of_publ'                  , 'default' ]
    - [ 'ANY'  , '/get_alias'                    , 'default' ]
    - [ 'ANY'  , '/get_project'                  , 'default' ]
    - [ 'ANY'  , '/get_department'               , 'default' ]
    - [ 'ANY'  , '/get_research_group'           , 'default' ]

    - [ 'ANY'  , '/department'                   , 'default' ]
    - [ 'ANY'  , '/publication'                  , 'default' ]
    - [ 'ANY'  , '/data'                         , 'default' ]
    - [ 'ANY'  , '/person'                       , 'default' ]
    - [ 'ANY'  , '/staffdirectory'               , 'default' ]
    - [ 'ANY'  , '/project'                      , 'default' ]
    - [ 'ANY'  , '/export'                       , 'default' ]
    - [ 'ANY'  , '/feed'                         , 'default' ]
    - [ 'ANY'  , '/mark'                         , 'default' ]
    - [ 'ANY'  , '/reorder'                      , 'default' ]
    - [ 'ANY'  , '/embed'                        , 'default' ]

    - [ 'ANY'  , '/rc/'                          , 'default' ]
    - [ 'ANY'  , '/download/'                    , 'default' ]
    - [ 'ANY'  , '/thumbnail/'                   , 'default' ]
    - [ 'ANY'  , '/livecitation'                 , 'defailt' ]

    - [ 'ANY'  , '/sru'                          , 'default' ]
    - [ 'ANY'  , '/oai'                          , 'default' ]

    - [ 'ANY'  , '/$'                            , 'default' ]
