_prefix:
  queue:

# Log directory for worker and supervisor log files
# logdir: logs

minion:
  Pg: "postgresql://librecat@/librecat_production"

minion_ui:
  username: changeme
  password: changeme

workers:
  - package: Datacite
    options:
      user: 'DEMO.XXX'
      password: 'secret'
    tasks:
      datacite: work
  - package: Mailer
    options:
      default_from: 'unknown@librecat.org'
    tasks:
      mailer: work

