_prefix:
  user:

roles:
  guest:
    rules:
      - can view publication if status public

  user:
    inherit: guest
    rules:
      - can add publication
      - can view publication own
      - can edit publication own
      - cannot edit publication if locked

  delegate:
    inherit: user
    rules:
      - can view publication owned_by
      - can edit publication owned_by

  reviewer:
    inherit: user
    rules:
      - can view publication affiliated_with
      - can edit publication affiliated_with

  #project_reviewer:

  #award_admin:

  #data_manager:

  super_admin:
    rules:
      - can *

