_prefix:
  roles:

guest:
  rules:
    - can view publication status public

user:
  inherit: guest
  rules:
    - can add publication
    - can view publication own
    - can edit publication own
    - cannot edit publication locked

delegate:
  inherit: guest
  params:
    - owner
  rules:
    - can view publication owned_by owner
    - can edit publication owned_by owner

reviewer:
  inherit: guest
  params:
    - department
  rules:
    - can view publication affiliated_with department
    - can edit publication affiliated_with department

#project_reviewer:

#award_admin:

#data_manager:

#super_admin:
  #rules:
    #- can * * *

