# LibreCat::Worker specific configuration options
_prefix:
  worker:

# Log directory for worker and supervisor log files
logdir: logs

Datacite:
  user: 'DEMO.XXX'
  password: 'secret'

# FileUploader options are defined in files.yml
# ImageResizer options are defined in files.yml

Mailer:
  default_from: 'unknown@librecat.org'
