# LibreCat::Worker specific configuration options
_prefix:
  worker:

# Log directory for worker and supervisor log files
logdir: logs

DataCite:
  base_url: 'https://mds.datacite.org'
  user: ''
  password: ''
  test_mode: ''

# FileUploader options are defined in files.yml
# ImageResizer options are defined in files.yml

Mailer:
  default_from: 'unknown@librecat.org'
