_prefix:
  worker:

logdir: logs

Datacite:
  user: 'DEMO.XXX'
  password: 'secret'

FileUploader:
  files:
    package: 'Simple'
    options:
      root: '/data2/librecat/file_uploads'

ImageResizer:
  files:
    package: 'Simple'
    options:
      root: '/data2/librecat/file_uploads'
  access:
    package: 'Simple'
    options:
      root: '/data2/librecat/access_uploads'
