_prefix:
  store:

search:
    options:
        bags:
          publication:
            cql_mapping:
                indexes:
                    foobar:
                      op:
                        '=': true
                        '<>': true
                      field: 'foobar'
                      description: "foobar index"
                    foobar_list:
                      op:
                        '=': true
                        '<>': true
                      field: 'foobar_list'
                      description: "foobar_list index"
